name       : haskell-mustache
version    : 2.3.1
release    : 2
source     :
    - https://hackage.haskell.org/package/mustache-2.3.1/mustache-2.3.1.tar.gz : ac8bf93d36fc766f54a54b72ddf71d1ab90864ca86bdce3415d2e69823fdb348
license    : BSD-3-Clause
component  : programming.haskell
summary    : A mustache template parser library.
description: |
    A mustache template parser library.
builddeps  :
    - haskell-cabal-install
    - haskell-cmdargs-devel
    - haskell-either-devel
    - haskell-th-lift-devel
    - haskell-yaml-devel
rundeps    :
    - devel:
        - haskell-cmdargs-devel
        - haskell-either-devel
        - haskell-th-lift-devel
        - haskell-yaml-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
