name       : haskell-mustache
version    : 2.3.0
release    : 1
source     :
    - http://hackage.haskell.org/package/mustache-2.3.0/mustache-2.3.0.tar.gz : 018863e578e971e393edc65dd7e0ed92a0e37fc152a47bb379fd8abd59537be0
license    : BSD-3-Clause
component  : programming.haskell
summary    : A mustache template parser library.
description: |
    A mustache template parser library.
builddeps  :
    - haskell-aeson
    - haskell-cabal-install
    - haskell-cmdargs
    - haskell-either
    - haskell-parsec
    - haskell-scientific
    - haskell-th-lift
    - haskell-yaml
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
